[workspace]
members = ["redfish-axum", "redfish-data", "example"]
# TODO: Add this later, for now it's annoying to remember special options to run example
#default-members = ["redfish-axum", "redfish-data"]