[package]
name = "redfish-data"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytes = "1.4.0"
mime = "0.3.17"
serde = "1.0.162"
serde_json = "1.0.95"